### ISSUE TITLE
Boot MX4SIO no working 

### ISSUE THREAD

**Issue by Kunihiko1897** [israpps/wLaunchELF_ISR#55]
When opening the MX4SIO boot and whether or not it has a USB, it stays on a black screen and the red control indicator turns off immediately after entering, why is this? It should be noted that I am using the I am using the latest version so far.

**Comment by JMaxxL** [comment]
Im getting same outcome, when i tried the BOOT-EXFAT-NO_NETWORK-MX4SIO.ELF (f26f45c) from yesterday it didn't just freeze my controller this time, it froze the entire PS2 on my 50000n.

I went back to WLE_ISR-REVERT_MX4SIOv1.2 and everything is working perfect

**Comment by israpps** [comment]
hi

Yes, issue is known already and i'm trying to find the cause of this issue

Please test this
[WLE_MX4SIO_TEST3.zip](https://github.com/israpps/wLaunchELF_ISR/files/12549470/WLE_MX4SIO_TEST3.zip)

**Comment by israpps** [comment]
if someone wants to perform some in depth testing

Please download [PS2CLIENT](https://github.com/ps2dev/ps2client/releases/tag/latest) and this [BOOT-EXFAT-MX4SIO-UDPTTY.zip](https://github.com/israpps/wLaunchELF_ISR/files/12549540/BOOT-EXFAT-MX4SIO-UDPTTY.zip)

Connect your PS2 and your PC with an ethernet cable

Unpack the PS2Client somewhere on your PC, open a terminal on  that same path And run

```bash
ps2client listen >LOG.TXT
```

Then and only then, run the wLaunchELF I send on this message on the console. if everything went alright, youll get debugging messages written on `LOG.TXT` use the wLE untill the issue arises, wait some seconds, shutdown console and then send me the log file

**Comment by JMaxxL** [comment]
Yes I will be happy to test & report back

I downloaded the client to connect my PS2 but was unable to get that far. Because the mx4sio will not show up at all even after re-inert BUT it is NOT freezing this time. I rebooted the console many times, to double check. The mx4sio dose not blink like it normally dose & when I go into mass it dose not pop up or replace mass like the old build did. 

I went into EVERYTHING "mc0 mc1 cd etc just to see what would happen & back out, mx4sio still did not pop up. 

If you have anything to test tonite I will be available & will keep checking back to see if you post any changed code.
I'm leaving town tomorrow but will be back in 3 weeks :-( 

But id like to help test the new build & be willing to connect debug client on my 50000n

**Comment by Kunihiko1897** [comment]
> hi
> 
> Yes, issue is known already and i'm trying to find the cause of this issue
> 
> Please test this [WLE_MX4SIO_TEST3.zip](https://github.com/israpps/wLaunchELF_ISR/files/12549470/WLE_MX4SIO_TEST3.zip)

With these, if it works in mx4sio, it no longer freezes or the control led turns off

**Comment by MayanKoyote** [comment]
Ok. It is very difficult for me to read and even more to understand what is written here, apparently there must have been a problem at some point in the translation.
But I understand that here discusses the problem with build f26f45c, and more specifically with those binaries that have in the name MX4SIO.
And the problem is somewhat similar to issue #52.

Here are my observations:
SCPH-77004, classic Bitfunx MX4SIO, BOOT-EXFAT-NO_NETWORK-MX4SIO.ELF f26f45c:
1. Only memory card with FMCB (and wLaunchELF) is inserted into slot 1, nothing else.
wLaunchELF starts, control works fine.
Startup of wLaunchELF looks like black screen -> brief blinking -> wLe board.
2. Memory card with FMCB (and wLaunchELF) is inserted into slot 1, Bitfunx MX4SIO is inserted into slot 2.
wLaunchELF does not start, just black screen.
3. Only memory card with FMCB (and wLaunchELF) is inserted into slot 1, nothing else.
wLaunchELF starts, control works fine. (same as case 1).
Next, inserting Bitfunx MX4SIO into slot 2.
wLaunchELF visually hangs: control does not work.

The following is what happened when using BOOT-EXFAT-MX4SIO-UDPTTY:
1. Only memory card with FMCB (and wLaunchELF) is inserted into slot 1, nothing else.
wLaunchELF starts, control works fine.
log file: [nothing_else_inserted.txt](https://github.com/israpps/wLaunchELF_ISR/files/12568580/nothing_else_inserted.txt)
2. Memory card with FMCB (and wLaunchELF) is inserted into slot 1, Bitfunx MX4SIO is inserted into slot 2.
wLaunchELF does not start, just black screen.
log file: [mx4sio_inserted_before_start.txt](https://github.com/israpps/wLaunchELF_ISR/files/12568581/mx4sio_inserted_before_start.txt)
3. Only memory card with FMCB (and wLaunchELF) is inserted into slot 1, nothing else.
wLaunchELF starts, control works fine. (same as case 1).
Next, inserting Bitfunx MX4SIO into slot 2.
wLaunchELF visually hangs: control does not work.
log file: [mx4sio_inserted_after_start.txt](https://github.com/israpps/wLaunchELF_ISR/files/12568582/mx4sio_inserted_after_start.txt)

**Comment by israpps** [comment]
Very odd indeed
